--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DNTxH/SkyWars-svile
build-by-default: true
branches:
- main
projects:
  SkyWars-svile:
    path: ""
 libs:
      - src: cooldogedev/BedrockEconomy/BedrockEconomy
        version: ^2.0.8
...
